name: Allan André
favicon: null
layout_spectrum: 0.99925
typography_spectrum: 0.61153
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131416'
    - '#3d3f3e'
    - '#bf2621'
    - '#a09ea3'
    - '#cdd6cf'
  brandStrength: 0.25981822656467557
  lightness: 0.5598679750692099
  saturation: 0.3984106339048594
  rhythmicContrast: 0.24688874394632876
purpose: []
