name: Allan André
favicon: null
layout_spectrum: 0
typography_spectrum: 0.48311
title: the art of Allan André
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f6f6f6'
    - '#333532'
    - '#c8c4b8'
    - '#878277'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
