name: Allan André
favicon: null
layout_spectrum: 0.25524
typography_spectrum: 0.61153
title: the art of Allan André
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dedbc9'
    - '#1e1e1c'
    - '#6b6a66'
    - '#b8b6aa'
    - '#8f8e89'
  brandStrength: 0.25981822656467557
  lightness: 1
  saturation: 0.3984106339048594
  rhythmicContrast: 0
purpose: []
