name: Allan André
favicon: null
layout_spectrum: 0.00909367180429399
typography_spectrum: 0.09371549030765891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.25981822656467557
  lightness: 0.5598679750692099
  saturation: 0.3984106339048594
  rhythmicContrast: 0.24688874394632876
purpose: []
